"""Add column url_cover to Songs table

Revision ID: 0fc2f57c0ffc
Revises: 1e6b0d645c92
Create Date: 2023-04-12 17:54:11.875733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fc2f57c0ffc'
down_revision = '1e6b0d645c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_cover', sa.VARCHAR(2083), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_column('url_cover')

    # ### end Alembic commands ###
