"""Add column short_description to authors table.

Revision ID: 191454fa78df
Revises: 5de377ec8490
Create Date: 2023-04-12 10:50:33.568084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '191454fa78df'
down_revision = '5de377ec8490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.Text(500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column(sa.Column('short_description'))

    # ### end Alembic commands ###
