"""Add column url_cover to albums table

Revision ID: 1e6b0d645c92
Revises: bc3cda25c968
Create Date: 2023-04-12 13:36:27.473061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e6b0d645c92'
down_revision = 'bc3cda25c968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_cover', sa.VARCHAR(2083), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('url_cover')
    # ### end Alembic commands ###
