"""Add column url_photo to authors.

Revision ID: 5de377ec8490
Revises: 1505d5cf84a3
Create Date: 2023-04-11 23:13:15.320331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5de377ec8490'
down_revision = '1505d5cf84a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_photo', sa.VARCHAR(2083), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('url_photo')

    # ### end Alembic commands ###
