"""Add foreign key to table playlists_songs

Revision ID: 88faaed269cf
Revises: d3684f3ac3a4
Create Date: 2023-04-12 12:12:22.496871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88faaed269cf'
down_revision = 'd3684f3ac3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_songs_id", "playlists_songs",
        "songs", ["id_s"], ["id_s"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_songs_id", "playlists_songs", type_="foreignkey")

    # ### end Alembic commands ###
