"""Add column title to playlists.

Revision ID: 9134d7788c6c
Revises: adbfdd7e5a53
Create Date: 2023-04-11 22:33:31.164596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9134d7788c6c'
down_revision = 'adbfdd7e5a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(40), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('title')


    # ### end Alembic commands ###
