"""Initial migration.

Revision ID: adbfdd7e5a53
Revises: 
Create Date: 2023-04-10 20:08:42.622157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbfdd7e5a53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genders',
    sa.Column('id_g', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2), nullable=False),
    sa.Column('description', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_g')
    )
    op.create_table('genres',
    sa.Column('id_g', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_g')
    )
    op.create_table('nationalities',
    sa.Column('id_n', sa.Integer(), nullable=False),
    sa.Column('nationality', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_n')
    )
    op.create_table('authors',
    sa.Column('id_a', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('nationality_id', sa.Integer(), nullable=False),
    sa.Column('number_of_songs', sa.Integer(), nullable=False),
    sa.Column('number_of_albums', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nationality_id'], ['nationalities.id_n'], ),
    sa.PrimaryKeyConstraint('id_a')
    )
    op.create_table('users',
    sa.Column('id_u', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gender'], ['genders.id_g'], ),
    sa.PrimaryKeyConstraint('id_u')
    )
    op.create_table('albums',
    sa.Column('id_a', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('number_of_songs', sa.Integer(), nullable=False),
    sa.Column('length_sec', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id_a'], ),
    sa.PrimaryKeyConstraint('id_a')
    )
    op.create_table('songs',
    sa.Column('id_s', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('number_of_plays', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id_a'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id_g'], ),
    sa.PrimaryKeyConstraint('id_s')
    )
    # ### end Alembic commands ###
    op.create_table('authors_songs',
                    sa.Column('id_a', sa.Integer, nullable=False),
                    sa.Column('id_s', sa.Integer, nullable=False),
                    sa.ForeignKeyConstraint(['id_a'], ['authors.id_a'], ),
                    sa.ForeignKeyConstraint(['id_s'], ['songs.id_s'], ),)
    op.create_table('playlists',
                    sa.Column('id_p', sa.Integer),
                    sa.Column('user_id', sa.Integer, nullable=False),
                    sa.Column('number_of_songs', sa.Integer, nullable=False),
                    sa.Column('length_sec', sa.Integer, nullable=False),
                    sa.Column('private', sa.Integer, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id_u']),
                    sa.PrimaryKeyConstraint('id_p'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('albums')
    op.drop_table('users')
    op.drop_table('authors')
    op.drop_table('nationalities')
    op.drop_table('genres')
    op.drop_table('genders')
    op.drop_table('authors_songs')
    op.drop_table('playlists')
    # ### end Alembic commands ###
