"""Add foreign keys to tables playlists_songs

Revision ID: d3684f3ac3a4
Revises: 191454fa78df
Create Date: 2023-04-12 12:01:47.507647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3684f3ac3a4'
down_revision = '191454fa78df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_playlist_id", "playlists_songs",
        "playlists", ["id_p"], ["id_p"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_playlist_id", "playlists_songs", type_="foreignkey")

    # ### end Alembic commands ###
